// ManaCue 共テ型演習（β）
//
// 大学入試センターの過去問を転載・改変したものではありません。
// 学習指導要領と公表されている問題作成方針を参考に作成し、
// 正答・解説・選択肢を確認した完全オリジナル問題だけを収録します。
const MANACUE_PRACTICE_QUESTIONS = [
  {
    id: 'eng-r-001',
    subjectId: 'english',
    unitId: 'eng_reading',
    topic: '複数テクスト読解（共通テスト型）',
    sectionId: 'eng_short',
    sectionLabel: '第1問型｜短い案内・メッセージ',
    difficulty: 'basic',
    stimulus: `Library Volunteer Day\n\n10:00  Staff meeting\n10:30  Volunteer orientation\n10:45  Doors open to visitors\n\nMessage from Aya:\nI will arrive at 10:20. I promised to work at the book-return desk after the doors open. Before that, I can help with one short task.`,
    prompt: 'Ayaが来館者の入場前に行うこととして、最も適切なものはどれか。',
    choices: [
      { id: 'A', text: '10時からスタッフ会議に参加する。' },
      { id: 'B', text: '案内表示を準備する短い作業を手伝う。' },
      { id: 'C', text: '10時20分から返却カウンターを担当する。' },
      { id: 'D', text: '来館者向けのオリエンテーションを行う。' },
    ],
    correctChoiceId: 'B',
    explanation: 'Ayaは10時20分に到着し、10時45分の開館後は返却カウンターを担当します。開館前の25分でできる短い作業を手伝う、という条件に合うのはBです。',
  },
  {
    id: 'eng-r-002',
    subjectId: 'english',
    unitId: 'eng_reading',
    topic: '複数テクスト読解（共通テスト型）',
    sectionId: 'eng_short',
    sectionLabel: '第1問型｜短い案内・メッセージ',
    difficulty: 'basic',
    stimulus: `School Café Notice\n\nReusable Cup Week: Monday–Friday\nBring your own cup and get 30 yen off any hot drink.\nThe discount cannot be used with other coupons. Cold drinks are not included.\n\nKen has a 50-yen coupon and wants a 300-yen hot tea. He brings his own cup.`,
    prompt: 'Kenが支払うことのできる最も安い金額はいくらか。',
    choices: [
      { id: 'A', text: '220円' },
      { id: 'B', text: '250円' },
      { id: 'C', text: '270円' },
      { id: 'D', text: '300円' },
    ],
    correctChoiceId: 'B',
    explanation: 'マイカップ割引30円と50円クーポンは併用できません。より割引額が大きい50円クーポンを使うと、300−50＝250円です。',
  },
  {
    id: 'eng-r-003',
    subjectId: 'english',
    unitId: 'eng_reading',
    topic: 'パラグラフリーディング',
    sectionId: 'eng_multi',
    sectionLabel: '第2問型｜複数資料の読み取り',
    difficulty: 'standard',
    stimulus: `Three students reviewed study spaces.\n\nMika: The town library is silent and has large desks, but it closes at 6 p.m.\nRui: The station café stays open until 9 p.m., although music is sometimes loud.\nSora: The school study room closes at 7 p.m. It is usually quiet, and students may discuss work in a separate area.\n\nYuto wants to study with a friend from 6:15 to 6:45 p.m. and needs to talk about a project.`,
    prompt: 'Yutoに最も適した場所はどれか。',
    choices: [
      { id: 'A', text: '町の図書館' },
      { id: 'B', text: '駅のカフェ' },
      { id: 'C', text: '学校の自習室' },
      { id: 'D', text: 'どの場所も条件を満たさない' },
    ],
    correctChoiceId: 'C',
    explanation: '図書館は6時に閉まり、カフェは会話できるものの音楽がうるさい場合があります。学校の自習室は6時45分まで開いており、話し合い用の場所もあるためCが最適です。',
  },
  {
    id: 'eng-r-004',
    subjectId: 'english',
    unitId: 'eng_reading',
    topic: '複数テクスト読解（共通テスト型）',
    sectionId: 'eng_multi',
    sectionLabel: '第2問型｜複数資料の読み取り',
    difficulty: 'standard',
    stimulus: `Eco Tour Options\n\nRiver Walk: 90 minutes / 1,200 yen / begins at 9:00 and 14:00\nForest Bike: 120 minutes / 2,400 yen / begins at 10:00\nBird Watch: 60 minutes / 1,500 yen / begins at 8:30 and 15:30\n\nEmi can start after 1 p.m., must finish by 4 p.m., and has 1,400 yen.`,
    prompt: 'Emiが参加できるツアーはどれか。',
    choices: [
      { id: 'A', text: '14時のRiver Walk' },
      { id: 'B', text: '10時のForest Bike' },
      { id: 'C', text: '15時30分のBird Watch' },
      { id: 'D', text: '参加できるツアーはない' },
    ],
    correctChoiceId: 'A',
    explanation: '14時のRiver Walkは15時30分に終わり、料金も1,200円です。ほかは開始時刻、終了時刻、予算のいずれかが条件に合いません。',
  },
  {
    id: 'eng-r-005',
    subjectId: 'english',
    unitId: 'eng_reading',
    topic: '読解のコツ',
    sectionId: 'eng_inference',
    sectionLabel: '第3問型｜文章の要点・推論',
    difficulty: 'standard',
    stimulus: `Many people think taking notes means writing down every sentence they hear. However, students who pause to choose key ideas often remember more. The act of deciding what matters connects new information to knowledge already in memory. For this reason, a short set of organized notes can be more useful than a complete record.`,
    prompt: '筆者が最も伝えたいことはどれか。',
    choices: [
      { id: 'A', text: '授業中はできるだけ速く全文を書き取るべきだ。' },
      { id: 'B', text: '短い授業ほど記憶に残りやすい。' },
      { id: 'C', text: '重要点を選んで整理することが理解を助ける。' },
      { id: 'D', text: '既に知っている内容はメモする必要がない。' },
    ],
    correctChoiceId: 'C',
    explanation: '本文は、全文の記録よりも「何が重要かを選び、既有知識と結び付ける」ことが記憶に役立つと述べています。',
  },
  {
    id: 'eng-r-006',
    subjectId: 'english',
    unitId: 'eng_reading',
    topic: '読解のコツ',
    sectionId: 'eng_inference',
    sectionLabel: '第3問型｜文章の要点・推論',
    difficulty: 'advanced',
    stimulus: `A city replaced some parking spaces with small public gardens. At first, nearby shop owners worried that fewer drivers would stop. Six months later, pedestrian traffic had increased, and several stores reported more afternoon customers. The result does not prove that every parking space should become a garden, but it suggests that streets can support business in more than one way.`,
    prompt: '本文から最も適切に推論できることはどれか。',
    choices: [
      { id: 'A', text: '公共庭園を作れば、すべての店の売上が必ず増える。' },
      { id: 'B', text: '車で来る客は歩行者より買い物をしない。' },
      { id: 'C', text: '道路空間の使い方は、来訪者の流れに影響し得る。' },
      { id: 'D', text: '店主たちは計画の開始前から庭園に賛成していた。' },
    ],
    correctChoiceId: 'C',
    explanation: '筆者は因果を断定せず、空間の変更後に歩行者と午後の客が増えた事実から、道路の使い方が人の流れに影響し得ると慎重に述べています。',
  },
  {
    id: 'math-001',
    subjectId: 'math',
    unitId: 'math1',
    topic: '二次関数',
    sectionId: 'math_i',
    sectionLabel: '第1問型｜数学I 小問・探究',
    difficulty: 'basic',
    stimulus: '関数 f(x)＝x²−6x＋5 を考える。',
    prompt: 'f(x)の最小値はいくつか。',
    choices: [
      { id: 'A', text: '−5' },
      { id: 'B', text: '−4' },
      { id: 'C', text: '4' },
      { id: 'D', text: '5' },
    ],
    correctChoiceId: 'B',
    explanation: 'f(x)＝(x−3)²−4 と平方完成できます。(x−3)²が0のとき最小なので、最小値は−4です。',
  },
  {
    id: 'math-002',
    subjectId: 'math',
    unitId: 'math1',
    topic: 'データの分析',
    sectionId: 'math_data',
    sectionLabel: '第2問型｜データ・図形の活用',
    difficulty: 'basic',
    stimulus: '5人の得点は、小さい順に 4、6、7、8、x 点で、平均点は7点であった。',
    prompt: 'xの値と、この5人の得点の中央値の組合せとして正しいものはどれか。',
    choices: [
      { id: 'A', text: 'x＝9、中央値＝7' },
      { id: 'B', text: 'x＝10、中央値＝7' },
      { id: 'C', text: 'x＝10、中央値＝8' },
      { id: 'D', text: 'x＝11、中央値＝8' },
    ],
    correctChoiceId: 'B',
    explanation: '合計は7×5＝35点なので、x＝35−(4＋6＋7＋8)＝10です。小さい順の中央、3番目は7点です。',
  },
  {
    id: 'math-003',
    subjectId: 'math',
    unitId: 'math1',
    topic: '三角比',
    sectionId: 'math_data',
    sectionLabel: '第2問型｜データ・図形の活用',
    difficulty: 'standard',
    stimulus: '0°＜θ＜90°で、tan θ＝3/4 である。',
    prompt: 'sin θの値はいくつか。',
    choices: [
      { id: 'A', text: '3/5' },
      { id: 'B', text: '4/5' },
      { id: 'C', text: '3/4' },
      { id: 'D', text: '4/3' },
    ],
    correctChoiceId: 'A',
    explanation: '直角三角形の対辺を3、隣辺を4とすると、斜辺は5です。したがってsin θ＝対辺/斜辺＝3/5です。',
  },
  {
    id: 'math-004',
    subjectId: 'math',
    unitId: 'mathA',
    topic: '場合の数・確率',
    sectionId: 'math_a',
    sectionLabel: '選択問題型｜数学A',
    difficulty: 'standard',
    stimulus: '区別できる2個の公平な6面体さいころを同時に投げる。',
    prompt: '出た目の和が8になる確率はいくつか。',
    choices: [
      { id: 'A', text: '1/6' },
      { id: 'B', text: '5/36' },
      { id: 'C', text: '1/8' },
      { id: 'D', text: '7/36' },
    ],
    correctChoiceId: 'B',
    explanation: '和が8になる組は(2,6)、(3,5)、(4,4)、(5,3)、(6,2)の5通りです。全36通りなので5/36です。',
  },
  {
    id: 'math-005',
    subjectId: 'math',
    unitId: 'mathA',
    topic: '整数の性質（ユークリッドの互除法など）',
    sectionId: 'math_a',
    sectionLabel: '選択問題型｜数学A',
    difficulty: 'standard',
    stimulus: '252と105の最大公約数を、ユークリッドの互除法を用いて求める。',
    prompt: '最大公約数はいくつか。',
    choices: [
      { id: 'A', text: '7' },
      { id: 'B', text: '14' },
      { id: 'C', text: '21' },
      { id: 'D', text: '42' },
    ],
    correctChoiceId: 'C',
    explanation: '252＝105×2＋42、105＝42×2＋21、42＝21×2です。最後の0でない余りは21なので、最大公約数は21です。',
  },
  {
    id: 'math-006',
    subjectId: 'math',
    unitId: 'mathA',
    topic: '場合の数・確率',
    sectionId: 'math_a',
    sectionLabel: '選択問題型｜数学A',
    difficulty: 'basic',
    stimulus: 'M、A、N、Aの4文字をすべて横一列に並べる。',
    prompt: '異なる文字列は何通りできるか。',
    choices: [
      { id: 'A', text: '6通り' },
      { id: 'B', text: '8通り' },
      { id: 'C', text: '12通り' },
      { id: 'D', text: '24通り' },
    ],
    correctChoiceId: 'C',
    explanation: '4文字の並べ方4!通りから、同じAの入れ替え2!通りを割るので、4!/2!＝12通りです。',
  },
  {
    id: 'joho-001',
    subjectId: 'joho',
    unitId: 'joho_society',
    topic: '情報セキュリティ',
    sectionId: 'joho_society_design',
    sectionLabel: '第1問型｜情報社会・デザイン',
    difficulty: 'basic',
    stimulus: '学校を名乗るメールに「本日中にアカウントを確認してください」というリンクがあり、リンク先でIDとパスワードの入力を求められた。送信元のドメインは学校公式のものと1文字だけ異なっている。',
    prompt: '最も適切な対応はどれか。',
    choices: [
      { id: 'A', text: '期限が近いので、すぐにリンクから入力する。' },
      { id: 'B', text: '友人にメールを転送し、入力できるか試してもらう。' },
      { id: 'C', text: 'リンクを開かず、公式サイトや学校窓口から事実を確認する。' },
      { id: 'D', text: 'パスワードの一部だけ入力して反応を見る。' },
    ],
    correctChoiceId: 'C',
    explanation: '送信元の偽装と緊急性を強調する文面はフィッシングの典型です。メール内リンクは使わず、別経路で公式情報を確認します。',
  },
  {
    id: 'joho-002',
    subjectId: 'joho',
    unitId: 'joho_design',
    topic: 'ユーザーインターフェース',
    sectionId: 'joho_society_design',
    sectionLabel: '第1問型｜情報社会・デザイン',
    difficulty: 'standard',
    stimulus: 'ある申込フォームでは、必須項目の未入力を赤色だけで示している。色覚の違いがある利用者にも分かりやすく改善したい。',
    prompt: '最も適切な改善はどれか。',
    choices: [
      { id: 'A', text: '赤色をさらに濃くする。' },
      { id: 'B', text: '赤色に加えて「必須」の文字と記号を表示する。' },
      { id: 'C', text: '必須項目をすべてページ上部へ移動する。' },
      { id: 'D', text: '背景全体を赤色にする。' },
    ],
    correctChoiceId: 'B',
    explanation: '色だけに情報を依存させず、文字や形でも同じ意味を伝えることで、多様な利用者が状態を識別しやすくなります。',
  },
  {
    id: 'joho-003',
    subjectId: 'joho',
    unitId: 'joho_program',
    topic: 'アルゴリズム（順次・分岐・繰り返し）',
    sectionId: 'joho_program',
    sectionLabel: '第3問型｜プログラミング',
    difficulty: 'standard',
    stimulus: `次の処理を実行する。\n\nx ← 1\n3回繰り返す:\n  x ← x × 2 ＋ 1`,
    prompt: '処理終了後のxの値はいくつか。',
    choices: [
      { id: 'A', text: '7' },
      { id: 'B', text: '9' },
      { id: 'C', text: '15' },
      { id: 'D', text: '17' },
    ],
    correctChoiceId: 'C',
    explanation: 'xは1→3→7→15と変化します。更新式を3回適用したあとの値は15です。',
  },
  {
    id: 'joho-004',
    subjectId: 'joho',
    unitId: 'joho_program',
    topic: '変数・配列・関数',
    sectionId: 'joho_program',
    sectionLabel: '第3問型｜プログラミング',
    difficulty: 'standard',
    stimulus: `配列 score には [72, 85, 68, 91] が入っている。次の処理を行う。\n\ncount ← 0\nscoreの各要素sについて:\n  もしsが80以上なら count ← count＋1`,
    prompt: '処理終了後のcountの値はいくつか。',
    choices: [
      { id: 'A', text: '1' },
      { id: 'B', text: '2' },
      { id: 'C', text: '3' },
      { id: 'D', text: '4' },
    ],
    correctChoiceId: 'B',
    explanation: '80以上の得点は85と91の2つなので、countは2です。',
  },
  {
    id: 'joho-005',
    subjectId: 'joho',
    unitId: 'joho_network',
    topic: 'ネットワークの仕組み（TCP/IP・DNS）',
    sectionId: 'joho_network',
    sectionLabel: '第4問型｜ネットワーク・データ',
    difficulty: 'basic',
    stimulus: 'Webブラウザに manacue.example のようなドメイン名を入力した。',
    prompt: 'DNSの主な役割として最も適切なものはどれか。',
    choices: [
      { id: 'A', text: 'ドメイン名に対応するIPアドレスを調べる。' },
      { id: 'B', text: 'Webページの文章を暗号化して保存する。' },
      { id: 'C', text: '通信する画像の大きさを自動的に圧縮する。' },
      { id: 'D', text: '利用者のパスワードが正しいか確認する。' },
    ],
    correctChoiceId: 'A',
    explanation: 'DNSは、人が扱いやすいドメイン名と、通信に使うIPアドレスを対応付ける仕組みです。',
  },
  {
    id: 'joho-006',
    subjectId: 'joho',
    unitId: 'joho_network',
    topic: '統計・相関・回帰',
    sectionId: 'joho_network',
    sectionLabel: '第4問型｜ネットワーク・データ',
    difficulty: 'standard',
    stimulus: 'ある学校で「1日の学習時間」と「小テスト得点」に正の相関が見られた。',
    prompt: 'この結果の解釈として最も適切なものはどれか。',
    choices: [
      { id: 'A', text: '学習時間を増やせば、全員の得点が必ず上がると証明された。' },
      { id: 'B', text: '得点が高いほど学習時間が短くなる傾向がある。' },
      { id: 'C', text: '2変数に関連はあるが、この結果だけで因果関係は断定できない。' },
      { id: 'D', text: '学習時間以外の要因は得点に影響しない。' },
    ],
    correctChoiceId: 'C',
    explanation: '相関は2変数が一緒に変化する傾向を示しますが、それだけでは一方が他方の原因だとは断定できません。',
  },
].map(question => Object.freeze({
  ...question,
  sourceType: 'manacue_original',
  reviewStatus: 'content_checked',
  version: 1,
}));
